apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
        - name: employee
          image: irshadpp/employee
          env:
            - name: MONGO_URI_EMPLOYEE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGO_URI_EMPLOYEE
            - name: SMTP_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SMTP_USER
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SMTP_PASSWORD
            - name: JWT_EMAIL_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_EMAIL_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: employee-srv
spec:
  selector:
    app: employee
  ports:
    - name: employee
      protocol: TCP
      port: 4000
      targetPort: 4000
