apiVersion: apps/v1
kind: Deployment
metadata:
  name: meet-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meet
  template:
    metadata:
      labels:
        app: meet
    spec:
      containers:
        - name: meet
          image: irshadpp/meet
          env:
            - name: MONGO_URI_MEET
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGO_URI_MEET
            - name: JWT_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_ACCESS_SECRET
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_REFRESH_SECRET
            - name: CLIENT_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CLIENT_URL
            - name: ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: ACCOUNT_SID
            - name: AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: AUTH_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: meet-srv
spec:
  selector:
    app: meet
  ports:
    - name: meet
      protocol: TCP
      port: 8000
      targetPort: 8000
