apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: irshadpp/users
          env:
            - name: MONGO_URI_USERS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGO_URI_USERS
            - name: SMTP_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SMTP_USER
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SMTP_PASSWORD
            - name: JWT_EMAIL_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_EMAIL_SECRET
            - name: JWT_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_ACCESS_SECRET
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_REFRESH_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: users-srv
spec:
  selector:
    app: users
  ports:
    - name: users
      protocol: TCP
      port: 3000
      targetPort: 3000
