apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
        - name: project
          image: irshadpp/project
          resources:
            requests:
              memory: "200Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: MONGO_URI_PROJECT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGO_URI_PROJECT
            - name: JWT_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_ACCESS_SECRET
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_REFRESH_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: project-srv
spec:
  selector:
    app: project
  ports:
    - name: project
      protocol: TCP
      port: 5000
      targetPort: 5000
