apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscription
  template:
    metadata:
      labels:
        app: subscription
    spec:
      containers:
        - name: subscription
          image: irshadpp/subscription
          resources:
            requests:
              memory: "200Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: MONGO_URI_SUBSCRIPTION
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGO_URI_SUBSCRIPTION
            - name: JWT_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_ACCESS_SECRET
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_REFRESH_SECRET
            - name: CLIENT_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CLIENT_URL
            - name: STRIPE_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: STRIPE_SECRET
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: STRIPE_WEBHOOK_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: subscription-srv
spec:
  selector:
    app: subscription
  ports:
    - name: subscription
      protocol: TCP
      port: 9000
      targetPort: 9000
