name: CI for Users Service

on: 
  push:
    paths:
      - 'users/**'
  pull_request:
    paths:
      - 'users/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd users && npm install && npm run test:ci
